### ISSUE TITLE
Asyncio applications have a mysterious [SELF] function

### ISSUE THREAD

**Issue by AggressivelyMeows** [joerick/pyinstrument#111]
![](https://nyc3.digitaloceanspaces.com/cerulean/screenshots/2020/12/firefox_Rujk3KwAOv.png)

The first function is labelled as [SELF] and i'm not sure how to interpret it. Is it how long the event loop took to get back to the function or something else?

For context, i'm creating a profiler before and closing it after every request in Sanic. Its a Flask-like asyncio powered web framework.

**Comment by joerick** [comment]
'Self time' is time spent inside the function that's not attributable to any children - so probably something that's happening inside the function directly. I'm not super familiar with async Python, but I _think_ that if your code hit an await, you'd see the flow control return to the run loop in your  sample, which doesn't look like what's happening here. Maybe the time really is spent inside the function `serve`?

**Comment by AggressivelyMeows** [comment]
But then wouldnt it collpase into the serve function time?

**Comment by AggressivelyMeows** [comment]
While attempting to figure this out, I found that PyInstrument only records the first await'ed task during the profile:
![](https://nyc3.digitaloceanspaces.com/cerulean/screenshots/2020/12/firefox_9gYn5DoCA5.png)

There should be the `get_post` function running with the `_` but it just shows the time waster function.

**Comment by joerick** [comment]
Hmm interesting! So the async/await stuff does preserve profiler state to keep call trees clean. Good to know!

**Comment by wxd** [comment]
Does this mean that `pyinstrument` cannot be (easily) combined with async frameworks?

I tried using [`fastapi-profiler`](https://github.com/sunhailin-Leo/fastapi_profiler/blob/main/fastapi_profiler/profiler_middleware/profiler.py#L44), which essentially does:
```python
profiler.start()

try:
    await self.app(scope, receive, wrapped_send)
finally:
    print(self._profiler.output_text(show_all=True))
```

The output seems to contain only framework calls:
```
5.590 run_forever  asyncio/base_events.py:557
`- 5.590 _run_once  asyncio/base_events.py:1784
   |- 5.477 select  selectors.py:553
   |  `- 5.476 kqueue.control  <built-in>:0
   `- 0.112 _run  asyncio/events.py:79
      `- 0.106 coro  starlette/middleware/base.py:36
         `- 0.106 __call__  fastapi_profiler/profiler_middleware/profiler.py:35
            `- 0.106 __call__  starlette/exceptions.py:56
               `- 0.106 __call__  starlette/routing.py:545
                  `- 0.106 handle  starlette/routing.py:219
                     `- 0.100 app  starlette/routing.py:38
                        `- 0.098 app  fastapi/routing.py:162
                           `- 0.079 serialize_response  fastapi/routing.py:82
```

PS: I apologize in advance for asking about another project here, but it seems to be related to this issue. Feel free to ignore this comment, though.

**Comment by joerick** [comment]
@wxd I don't know the specifics of fastapi-profiler, but as long as there is only one profiler running at once, it should still work. if you remove the show_all, it should collapse all the framework stuff :)

**Comment by joerick** [comment]
Some experimentation I've done on this-

```
import asyncio
import pyinstrument
import time


def do_nothing():
    pass

def busy_wait(duration):
    end_time = time.time() + duration

    while time.time() < end_time:
        do_nothing()

async def say(what, when):
    p = pyinstrument.Profiler()
    p.start()

    busy_wait(0.1)
    await asyncio.sleep(when)
    busy_wait(0.1)

    p.stop()

    print(what)
    p.print(show_all=True)

loop = asyncio.get_event_loop()

loop.create_task(say('first hello', 2))
loop.create_task(say('second hello', 1))
loop.create_task(say('third hello', 3))

loop.run_forever()
loop.close()
```

This produces a nonsensical output, that looks like this:

```text
second hello

  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:23:58  Samples:  100
 /_//_/// /_\ / //_// / //_'/ //     Duration: 1.201     CPU time: 0.301
/   _/                      v3.4.1

Program: examples/async_experimentation.py

0.100 say  async_experimentation.py:15
└─ 0.100 busy_wait  async_experimentation.py:9
   ├─ 0.055 [self]  
   ├─ 0.031 time  <built-in>:0
   └─ 0.014 do_nothing  async_experimentation.py:6


first hello

  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:23:58  Samples:  100
 /_//_/// /_\ / //_// / //_'/ //     Duration: 2.201     CPU time: 0.504
/   _/                      v3.4.1

Program: examples/async_experimentation.py

0.100 say  async_experimentation.py:15
└─ 0.100 busy_wait  async_experimentation.py:9
   ├─ 0.055 [self]  
   ├─ 0.027 time  <built-in>:0
   └─ 0.018 do_nothing  async_experimentation.py:6


third hello

  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:23:58  Samples:  201
 /_//_/// /_\ / //_// / //_'/ //     Duration: 3.205     CPU time: 0.406
/   _/                      v3.4.1

Program: examples/async_experimentation.py

1.100 _run_once  asyncio/base_events.py:1784
├─ 0.900 select  selectors.py:553
│  └─ 0.900 kqueue.control  <built-in>:0
└─ 0.200 _run  asyncio/events.py:79
   └─ 0.200 say  async_experimentation.py:15
      └─ 0.200 busy_wait  async_experimentation.py:9
         ├─ 0.122 [self]  
         ├─ 0.052 time  <built-in>:0
         └─ 0.026 do_nothing  async_experimentation.py:6

```

Note that the durations don't match the top-level frame, indicating that some samples have got lost along the way. It took me a while to figure out that of course this is multiple Profiler objects trying to run on the same thread, and because of how Python profiling works, you can't have more than one setprofile target on one thread. I've since added an exception for this, because it's very easy to do. See 7d8ce2aeb0f4cac8717a309fdffbf8afad15db8f.

Now I'm trying something a little different, like this:

```
import asyncio
import pyinstrument
import time

def do_nothing():
    pass

def busy_wait(duration):
    end_time = time.time() + duration

    while time.time() < end_time:
        do_nothing()

async def say(what, when, profile=False):
    if profile:
        p = pyinstrument.Profiler()
        p.start()

    busy_wait(0.1)
    sleep_start = time.time()
    await asyncio.sleep(when)
    print(f'slept for {time.time() - sleep_start:.3f} seconds')
    busy_wait(0.1)

    print(what)
    if profile:
        p.stop()
        p.print(show_all=True)

loop = asyncio.get_event_loop()

loop.create_task(say('first hello', 2, profile=True))
loop.create_task(say('second hello', 1))
loop.create_task(say('third hello', 3))

loop.run_forever()
loop.close()
```

So I'm still starting the profiler in the coroutine, but I'm ensuring there's only one of them. Here's the output:

```text
slept for 1.006 seconds
second hello
slept for 2.006 seconds
first hello

  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:34:04  Samples:  504
 /_//_/// /_\ / //_// / //_'/ //     Duration: 2.206     CPU time: 0.505
/   _/                      v3.4.1

Program: examples/async_experimentation.py

2.205 _run_once  asyncio/base_events.py:1784
├─ 1.702 select  selectors.py:553
│  └─ 1.702 kqueue.control  <built-in>:0
└─ 0.503 _run  asyncio/events.py:79
   └─ 0.503 say  async_experimentation.py:17
      └─ 0.500 busy_wait  async_experimentation.py:10
         ├─ 0.271 [self]  
         ├─ 0.154 time  <built-in>:0
         └─ 0.075 do_nothing  async_experimentation.py:6


slept for 3.005 seconds
third hello
```

So... also very confusing! We were expecting busy_wait to contain 0.2 seconds of waiting, but It contained 0.5! And the sleep is showing as only 1.7 seconds long despite the fact that we know it was 2.006 seconds as measured inside the function.

But, actually this is because of how asyncio is interleaving these coroutines. The extra time spent in `busy_wait` is actually from the other coroutines doing their work. And the reduced sleep time is because while the first coroutine was 'sleeping', actually it was doing other coroutines' work!

**Comment by joerick** [comment]
> While attempting to figure this out, I found that PyInstrument only records the first await'ed task during the profile:

I suspect the real reason for this is that you had multiple Profilers running @AggressivelyMeows. So the information gathered in the first was truncated? If I'm right, if you try again with the latest code from `master`, you'll see the new exception from 7d8ce2aeb0f4cac8717a309fdffbf8afad15db8f.

> Hmm interesting! So the async/await stuff does preserve profiler state to keep call trees clean. Good to know!

This appears to be false, which makes a lot more sense.

---

Reflections on this for async profiling: 

Starting a Pyinstrument profiler from within a coroutine is asking for trouble. It's quite easy to hit the new exception in 7d8ce2aeb0f4cac8717a309fdffbf8afad15db8f, but also, because of how the run loop works, the sample is going to contain unrelated code from other coroutines.

**Instead, I'd recommend profiling the application as a whole** - starting the profiler before entering the run loop, and stopping it and outputting after the run loop has finished (or you press ctrl-c). You'll have to dig through more clutter, but I believe that this is currently the only way to get accurate results that reflect the execution of the async program. (or, if you have sync pockets of an async program, you could still wrap those in profilers. But, anything that hits an `await` is potentially suspect!)

^@sunhailin-Leo I haven't looked in detail at your fastapi profiler but you might be interested in this!

**Comment by sandeeppilania** [comment]
I am new in using Profilers and working on a  Fastapi project and tried using your profiler as well as fastapi-profiler but in both as the cases i get only the framework level tracing, where in i need the tracing and timings for each of the internal methods call in order to find out which model in the pipeline is consuming the most of time. 
![image](https://user-images.githubusercontent.com/38011316/114238418-93255f00-9952-11eb-9129-a3f19e10621b.png)
Do i need to start profile on each project package in order to get details of all the methods, right now what i have tried is starting the profiler on fastapi api request and capturing it before sending the response.
Would really appreciate any help here.

**Comment by joerick** [comment]
@AggressivelyMeows pyinstrument 4.0 has full async/await support, which should resolve your issues here.

@sunhailin-Leo it might be worth checking how your profiler works with the new functionality.

@sandeeppilania check out the `show_all` argument of Profiler.print()
