### ISSUE TITLE
Incorrect Session.program when running a module

### ISSUE THREAD

**Issue by matthiasdiener** [joerick/pyinstrument#241]
Due to `sys.argv` modifications (in `__main__.py`?), the program name is stored incorrectly in `Session.program`:

actual output:
```console
$ pyinstrument -m mpi4py t.py -a 
Program: mpi4py -a
```

expected output:
```console
$ pyinstrument -m mpi4py t.py -a 
Program: mpi4py t.py -a
```

**Comment by joerick** [comment]
I _think_ the issue here is that changing sys.argv is pretty common in these styles of wrapper scripts. pyinstrument, [mpi4py](https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/run.py#L31), cProfile all do it. Each time it happens, each script doesn't reset the value once the script has finished running, because each assumes it's the top-level script.

My thought is that we should consider changing sys.argv a 'patch' - i.e. it should be reset to it's previous value once the code has finished. I'll push a PR of a fix that I think works, and _should_ make more sense.
