### ISSUE TITLE
Pyinstrument doesn't capture context_changed event when started outside the ioloop

### ISSUE THREAD

**Issue by wouterdb** [joerick/pyinstrument#333]
# Problem

When pyinstrument is started outside of the ioloop, async calls are not correctly captured 

# How to reproduce 

When running 

```python
from pyinstrument import Profiler

profiler = Profiler(async_mode="enabled")
async def main():
    with profiler:
        await asyncio.sleep(2)

asyncio.run(main())

profiler.write_html("pyinst.html")
```

the trace produced is correct 
![image](https://github.com/user-attachments/assets/30d2d9bc-fb39-48f1-8253-b0d65002baa0)

When running 

```python
from pyinstrument import Profiler

profiler = Profiler(async_mode="enabled")
async def main():
        await asyncio.sleep(2)

with profiler:
    asyncio.run(main())

profiler.write_html("pyinst2.html")
```

the trace produced is not correct

![image](https://github.com/user-attachments/assets/eb48490a-d68a-4238-8e40-be6097719e5c)

I've traced this down to the '_sample' not being called by the underlying c function 'profile' for the 'context_changed' event. I haven't dug down into the C code.

Thank you for building this very cool profiler. 

Wouter

**Comment by joerick** [comment]
Actually, both are correct! It's a matter of perspective. 

When you `await` a `sleep`, your function is paused- similar to how `yield` works if you've come across that. The run loop in asyncio actually does the sleep, which is what you see in the second profile. This is also what you see when the async mode is turned off. 

I guess that you'd rather see the first output regardless of where the profiler is started. This isn't possible for a number of reasons. As an example, consider when there are multiple async tasks running simultaneously. When A is sleeping, B might be reading a file, while C is occasionally doing some work and going back to sleep. So it's only true that we're 'sleeping' from A's perspective, which is why the profiler has to be started inside A to get that readout.

**Comment by wouterdb** [comment]
Thank you for the prompt response. 

I agree that both are correct, but would indeed prefer the first output.

In fact, I would like to see every await as a call edge in the trace. 
To me, the following programs are conceptually the same and I would expect a similar call graph from them. 

```python
def main():
  time.sleep(2)
```

```python
async def main():
   await asynio.sleep(2) 
```

**Pyinstrument gets closest of all things I have tried.** 

I've been digging deep into this and I don't quite understand how you do it. 
Am I correct that 
- you track context changes to keep the profile limited to a specific scope 
- you keep track of the coroutine returns to build a virtual 'stack' ?

# More context 

I've done some further digging and I've found out that the graph of what awaits what could be built by doing 

```python
def record_trace():
    for task in asyncio.all_tasks():
        print(task, task._coro, task._coro.cr_await)
```

Which could be used for a snapshotting profilers, but I don't see how to use it in a way that is sufficiently performant for use here.

The only place I could find in the python domain, where task dependence could be tracked completely is `call_soon`, but for await statements is gets a `<Handle <TaskStepMethWrapper object at 0x7f8dab0c3520>()>`  and `TaskStepMethWrapper`  is/seems completely opaque in python: you can't get to the underlying coros 

I also haven't found a way to get a coroutine object from its associated frame. 

So I would really like to understand how you do it as  I have no better alternative.

# Why I want this

I want to make performance traces of [a highly parallel asyncio application, with an complex load profile and and some quite complicated locking in there and lots of IO](https://github.com/inmanta/inmanta-core/). I need to be able to trace all calls (not just one logical thread) and be able to correctly attribute what is waiting for what. 

I've tried open telemetry, but that itself has a very high performance penalty (even when off it seems), so now I have one more thing to profile. 

The only option I have left it is to add timers to the code and gradually move them closer to the hot-spot.

**Comment by joerick** [comment]
What you want simply isn't possible in pyinstrument, because all of pyinstrument, and the core data structure (time-linear stack snapshots) assumes a single thread of operation i.e. one thing is happening at once. Every time we sample the stack, we attribute the time elapsed to the thing the program was just doing - in pyinstrument, that's either 'in-context' (normal sync code)  or 'out-of-context' (attributable to an await).

Perhaps you should try writing your own profiler! BTW, the way that pyinstrument tracks awaits (using an '[await stack](https://github.com/Carreau/pyinstrument/blob/fdc6a6924d867f1ef274f067e816bb3f75d7253d/pyinstrument/low_level/stat_profile.c#L615)') also probably wouldn't work for what you're after, because it can only detect an await from the context of a single task, using the change of a contextlib variable to do so. The `asyncio.all_tasks` snippet above looks like the best approach IMO. Maybe you can build a mechanism so it only samples occasionally.

**Comment by wouterdb** [comment]
Thank you for the explanation! 

I didn't know pyinstrument is 'single-thread', but it explains why I couldn't get my head around your code to track async tasks. 

I'm looking into writing my own profiler, but that will take time. 
I've found `PyFrame_GetGenerator(frame);`  in the C api, this allows tracking wait_for relations efficiently, but the stack structure is a lot more complicate then I assumed, so it will take time.

**Comment by joerick** [comment]
`PyFrame_GetGenerator(frame)` looks really useful! Thanks for mentioning it... I might have written pyinstrument's async support differently had that been available. But I don't want 3.11 as a minimum for a few years yet.
